export const DEFAULT_BUNDLE_KEY = '__default_bundle__'
export const BASE_POLICY_NAME = '__base_unlimited__'

export const BASE_GRANT_PROGRAMS = [
  {
    program_code: 'one_time_xusd',
    name: 'One-time XUSD Top-up',
    cadence: 'once' as const,
    window_default_seconds: 31_536_000,
    window_kind: 'fixed' as const,
    priority: 10,
    on_ledger: true,
    issue_anchor: 'binding_start' as const,
    issuance_mode: 'eager',
    periodic_accounting: false,
    accrual_mode: 'full_at_period_start',
    metadata: { description: 'One-time wallet purchase; amount set by bindings' },
  },
  {
    program_code: 'daily_xusd',
    name: 'Daily XUSD',
    cadence: 'daily' as const,
    window_default_seconds: 86_400,
    priority: 50,
    on_ledger: false,
    metadata: { description: 'Daily grant template; amount set by bindings' },
  },
  {
    program_code: 'weekly_xusd',
    name: 'Weekly XUSD',
    cadence: 'weekly' as const,
    window_default_seconds: 604_800,
    priority: 50,
    on_ledger: false,
    metadata: { description: 'Weekly grant template; amount set by bindings' },
  },
  {
    program_code: 'monthly_xusd',
    name: 'Monthly XUSD',
    cadence: 'monthly' as const,
    window_default_seconds: 2_592_000,
    priority: 20,
    on_ledger: true,
    metadata: { expiry_policy: 'forfeit', description: 'Monthly grant template; amount set by bindings' },
  },
  {
    program_code: 'period_xusd',
    name: 'Billing Period XUSD',
    cadence: 'billing_period' as const,
    window_kind: 'period' as const,
    priority: 20,
    on_ledger: true,
    metadata: { expiry_policy: 'forfeit', description: 'Grant aligned to billing period; amount set by bindings' },
  },
  {
    program_code: 'quarterly_xusd',
    name: 'Quarterly XUSD',
    cadence: 'quarterly' as const,
    window_default_seconds: 7_776_000,
    priority: 20,
    on_ledger: true,
    metadata: { expiry_policy: 'forfeit', description: 'Quarterly grant template; amount set by bindings' },
  },
  {
    program_code: 'yearly_xusd',
    name: 'Yearly XUSD',
    cadence: 'yearly' as const,
    window_default_seconds: 31_536_000,
    priority: 50,
    on_ledger: true,
    metadata: { expiry_policy: 'forfeit', description: 'Yearly grant template; amount set by bindings' },
  },
]
